# Ansible configuration
ansible_become: true

# Kubernetes configuration
kubernetes_version: "1.29"
pod_network_cidr: "10.244.0.0/16"

# Container Runtime
cri_socket: "unix:///var/run/cri-dockerd.sock"

# Network
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/calico.yaml"

# User configuration
cluster_user: "{{ ansible_user }}"
