kubernetes_version: "1.29"
pod_network_cidr: "192.168.0.0/16"
cri_socket: "unix:///var/run/cri-dockerd.sock"

calico_manifest_url: "https://docs.projectcalico.org/manifests/calico.yaml"
cluster_user: "{{ ansible_user }}"
