- name: Check cluster initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: cluster_init

- name: Initialize cluster
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --cri-socket={{ cri_socket }}
  when: not cluster_init.stat.exists

- name: Create kube directory
  file:
    path: ~/.kube
    state: directory

- name: Copy kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes

- name: Install Calico network
  command: kubectl apply -f {{ calico_manifest_url }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_cmd

- name: Save join command
  set_fact:
    kube_join_cmd: "{{ join_cmd.stdout }} --cri-socket={{ cri_socket }}"
